# Generated by Django 2.2.5 on 2019-09-15 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApiModule', '0003_auto_20190915_0757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_on', models.CharField(max_length=200)),
                ('changed_from', models.CharField(max_length=200)),
                ('changed_to', models.CharField(max_length=200)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiModule.Order')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_on', models.CharField(max_length=200)),
                ('changed_from', models.CharField(max_length=200)),
                ('changed_to', models.CharField(max_length=200)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiModule.FoodItem')),
            ],
        ),
    ]
