# Generated by Django 2.2.4 on 2019-09-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emp_id',
            field=models.UUIDField(default='b676dc7c572947298d1603d6ed2e8a32', unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiModule.StaffPosition'),
        ),
    ]
