# Generated by Django 2.2.5 on 2019-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0002_auto_20190911_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emp_id',
            field=models.UUIDField(default='6df05176960942838a9391eca8992098', unique=True),
        ),
    ]
