# Generated by Django 2.2.4 on 2019-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0002_auto_20190809_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('REFUND', 'REFUND')], default='PENDING', max_length=8),
        ),
    ]
