# Generated by Django 2.2.4 on 2019-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0003_auto_20190818_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8),
        ),
    ]
