# Generated by Django 2.2.4 on 2019-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0004_auto_20190824_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('DONE', 'Done'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8),
        ),
    ]
