# Generated by Django 2.2.4 on 2019-08-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0005_auto_20190830_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='fooditem/'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(null=True, upload_to='foodtype/'),
        ),
    ]
