# Generated by Django 2.2.4 on 2019-08-31 04:59

import ApiModule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0006_auto_20190831_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to=ApiModule.models.user_directory_path),
        ),
    ]
