# Generated by Django 2.2.4 on 2019-08-31 05:40

import ApiModule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiModule', '0007_auto_20190831_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ApiModule.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ApiModule.models.foodtype_directory_path),
        ),
    ]
